name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NGINX
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd /var/nginx
            docker-compose down
            cd /var
            rm -rf /var/nginx
            mkdir /var/nginx
            chmod 777 /var/nginx
            git clone git@github.com:joshhills/joshhills-nginx.git .
            cd /var/nginx
            chmod +x init-letsencrypt.sh
            # docker-compose up -d
